### PR TITLE
Add new tool SnakeEyesConfig

### PR DESCRIPTION
**Pull request by jakobsack**
This is a tool I wrote to make the generation of SnakeEyes config files easier. Although the program has some rough edges you already can use it to create and modify config files.

If you do not want this in the main repository I'll keep the program on my own profile-

### CODE REVIEW

**Comment by snakefoot** [comment]
@jakobsack I'm considering to merge SnakeEyesConfig with SnakeEyesClient. Would it make sense to you?

**Comment by jakobsack** [comment]
Hi @snakefoot that would make sense to me. This also has the advantage that the user can see the probe results right away.

**Comment by snakefoot** [comment]
@jakobsack Should I merge them together, or can you do it?

**Comment by jakobsack** [comment]
It'd be great if you could do it as I currently do not have the resources to merge it.

**Pull request merged**
